var BLOCK_SIZE = 50,
    BLOCK_HALF = 25,
    RENDERER_X = 600,
    RENDERER_Y = 800,
    //ROW_SIZE = RENDERER_X / BLOCK_SIZE,
    ROW_SIZE = 12,
    RENDERER_COLOR = 0xA9A9A9,
    INITIAL_DROPSPEED = 2;
